package com.bignerdranch.android.androidacademy

data class Movies(
    val backdrop: Backdrop,
    val budget: Budget,
    val countries: List<Country>,
    val description: String,
    val distributors: Distributors,
    val externalId: ExternalId,
    val facts: List<Fact>,
    val fees: Fees,
    val genres: List<Genre>,
    val id: Int,
    val images: Images,
    val lists: List<Any>,
    val movieLength: Int,
    val name: String,
    val persons: List<Person>,
    val poster: Poster,
    val premiere: Premiere,
    val productionCompanies: List<ProductionCompany>,
    val rating: Rating,
    val seasonsInfo: List<Any>,
    val slogan: String,
    val spokenLanguages: List<SpokenLanguage>,
    val status: String,
    val type: String,
    val videos: Videos,
    val votes: Votes,
    val year: Int
)